server:
  port: 8080

logging:
  level:
    root: info
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/log
    username: myuser
    password: secret
  servlet: # 上传文件，下载文件限制（默认1MB）
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main: # 允许循环依赖
    allow-circular-references: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl